### ISSUE TITLE
Login Failure Bad or Missing Credential

### ISSUE THREAD

**Issue by accad** [Texiwill/aac-lib#18]
Trying to figure this one out.

Username and password are 100% correct, copy and paste to/from browser just to eliminate typos.

OS: CentOS 7 

$ ./vsm.sh -y -u <redacted> -p <redacted>
Using the following options:
        Version:        6.7.4
        Username:               <redacted>
        Save Credentials:       0
        OS Mode:        centos
        VSM XML Dir:    /data/vmware-vsmxml
        Repo Dir:       /data/vmware-depot
        Dryrun:         0
        Rebuild:        0
        Force Download: 0
        Checksum:       1
        Historical Mode:0
        Symlink Mode:   1
        Reset XML Dir:  0
        Nested: 0
        Use credstore:  1
        Saving to /home/cecadmin/.vsmrc
        Authenticating... May take up to 90s... 12-20s is normal...  
TimeoutError: waiting for selector `.ng-star-inserted` failed: timeout 90000ms exceeded
    at new WaitTask (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:601:34)
    at DOMWorld.waitForSelectorInPage (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:502:26)
    at Object.internalHandler.waitFor (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:32:77)
    at DOMWorld.waitForSelector (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:385:29)
    at Frame.waitForSelector (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:971:51)
    at Page.waitForSelector (/data/vmware-vsmxml/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2414:33)
    at /data/vmware-vsmxml/node-bm.js:68:13
        Login Failure Bad or Missing Credential

What can I do here? Anything I can give you?

**Comment by Texiwill** [comment]
Please use --clean option to recreate. The login was successful but the website did not display properly. This happens when there is a issue with VMware's website. I ran this on Fedora this AM with no issues. I have seen this when VMware's site or the proxies are having issues.

**Comment by accad** [comment]
I must have done this 50 times, but only after YOU told me to do it it worked.

IT aura much?

Thanks for looking into it, great work btw, much nicer than VMware's solution.

If I can make one suggestion: the Exit and Back options, make them consistent, like 0,1 or E, B.

Finger/muscle memory hates your menus :)

Thanks again.

**Comment by Texiwill** [comment]
Hello,

E(xit), A(ll), and B(ack) do work. :) Glad it works for you now!

Best regards,
Edward L. Haletky
